language: node_js
node_js:
  - 8
python:
- "3.6"
cache:
  directories:
    - node_modules
before_install:
  # set up awscli packages
  - pip3 install --user awscli
script:
    - npm run build
    - npm test
deploy:
  - provider: script
    script: aws s3 sync build/ s3://$AWS_BUCKET_NAME
    skip_cleanup: true
    on:
      branch: master
