language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_install:
  # set up awscli packages
  - pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
    - npm run build
    - npm test
deploy:
  - provider: script
    script: aws s3 sync build/ s3://$AWS_BUCKET_NAME
    skip_cleanup: true
    on:
      branch: master
