language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
    - npm run build
    - npm test
deploy:
  - provider: script
    script: aws s3 sync build/ s3://$AWS_BUCKET_NAME
    skip_cleanup: true
    on:
      branch: master
